# Generated by Django 6.0.2 on 2026-03-10 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('surnom', models.CharField(blank=True, max_length=25, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('mere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mere_de', to='djens.individu')),
                ('pere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pere_de', to='djens.individu')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('individu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djens.individu')),
                ('nom_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('prenoms', models.CharField(max_length=100)),
                ('prenom_usuel', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('djens.individu',),
        ),
        migrations.CreateModel(
            name='Cheval',
            fields=[
                ('individu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djens.individu')),
                ('affixe', models.CharField(blank=True, max_length=15, null=True)),
                ('robe', models.CharField(blank=True, max_length=200, null=True)),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djens.race')),
            ],
            options={
                'abstract': False,
            },
            bases=('djens.individu',),
        ),
    ]
