# Generated by Django 6.0.2 on 2026-03-11 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individu',
            name='mere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mere_de', to='djens.individu'),
        ),
        migrations.AlterField(
            model_name='individu',
            name='pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pere_de', to='djens.individu'),
        ),
    ]
