# Generated by Django 6.0.2 on 2026-02-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='usage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='surnom',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
