# Generated by Django 6.0.2 on 2026-03-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0002_alter_individu_mere_alter_individu_pere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheval',
            name='affixe_avant',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
