# Generated by Django 6.0.2 on 2026-02-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0002_individu_usage_alter_individu_surnom'),
    ]

    operations = [
        migrations.AddField(
            model_name='individu',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='surnom',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='individu',
            name='usage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
