# Generated by Django 6.0.2 on 2026-02-06 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0003_individu_date_naissance_alter_individu_surnom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individu',
            name='prenoms',
        ),
        migrations.RemoveField(
            model_name='individu',
            name='usage',
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('individu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djens.individu')),
                ('nom_usage', models.CharField(blank=True, max_length=100, null=True)),
                ('prenoms', models.CharField(max_length=100)),
                ('prenom_usuel', models.CharField(max_length=30)),
            ],
            bases=('djens.individu',),
        ),
    ]
