# Generated by Django 6.0.2 on 2026-02-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0004_remove_individu_prenoms_remove_individu_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('type_union', models.CharField(blank=True, max_length=25, null=True)),
                ('parent1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djens.personne')),
                ('parent2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjoint', to='djens.personne')),
            ],
        ),
    ]
