# Generated by Django 6.0.2 on 2026-02-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0005_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='enfnats',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
