# Generated by Django 6.0.2 on 2026-02-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djens', '0006_union_enfnats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='enfnats',
        ),
    ]
